name: Android Build

on:
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1

        - name: Set Up JDK
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Check Android Lint
          run: ./android/gradlew lint

        - name: Run Tests
          run: ./android/gradlew test

        - name: Build Project
          run: ./android/gradlew assemble