name:  Mirror 

on:
  push:
    branches: 
      - 'master'

jobs:

  copy:
    name: Copy master branch to Mirror branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master 
      - name: Push to mirror-android
        run: git push master mirror-android
        

  mirror:
    name: Mirror to Gitlab branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: mirror-android # name of the remote branch


      - name: Mirror to gitlab
        uses: spyoungtech/mirror-action@master
        with:
          REMOTE: 'https://gitlab.com/polytechnique-montr-al/log3900/20-3/equipe-106/log3900-106.git'
          GIT_USERNAME: kevinNguyenPolyMTL
          GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
          PUSH_ALL_REFS: 'false'
          GIT_PUSH_ARGS: '-u'